package spaceinvaders.features.campaign;

/** Card definitions. Prerequisites are evaluated by {@link RunUpgrades}. */
public enum UpgradeId {
    MAX_HEALTH("Max Health", "+3 maximum HP and heal 3.", "Stronger armor may help you survive.", 5), ARMOR("Armor", "Reduce incoming damage.", "Plating could soften incoming fire.", 3), MOVEMENT("Movement", "Increase player movement speed only.", "Faster footwork keeps you alive.", 4), RECOVERY("Recovery", "Slowly regenerate health after avoiding damage.", "A medic could keep the squad standing.", 3), XP_GAIN("XP Gain", "Earn 15% more XP per rank.", "Experience can be put to better use.", 3), EMERGENCY_SAVE("Emergency Save", "The first lethal hit leaves you at 1 HP.", "There may be one last chance.", 1),
    BLASTER_DAMAGE("Blaster Damage", "+1 blaster damage.", "More power can be routed to your rifle.", 5), FIRE_RATE("Fire Rate", "Decrease blaster cooldown only.", "Your rifle can cycle faster.", 4), BOLT_SPEED("Bolt Speed", "Increase blaster bolt speed only.", "A faster bolt is harder to evade.", 3), MULTI_SHOT("Multi Shot", "Fire an additional blaster bolt.", "One trigger pull could cover more sky.", 2), PIERCING("Piercing", "Blaster bolts pass through additional enemies.", "A bolt could punch through a formation.", 3), SMART_BULLETS_UNLOCK("Smart Bullets", "Blaster bolts gain gentle target seeking.", "Your shots could learn to hunt.", 1), SMART_BULLET_TRACKING("Smart Tracking", "Improve blaster homing strength.", "A bolt can learn to turn.", 3), SMART_BULLET_RANGE("Smart Range", "Seek targets from farther away.", "A hunter needs a longer view.", 3),
    MISSILE_LAUNCHER("Missile Launcher", "SPACE also fires missiles on its own cooldown.", "A launcher waits in the arsenal.", 1), MISSILE_DAMAGE("Missile Damage", "+2 missile damage.", "A larger warhead awaits.", 4), MISSILE_COOLDOWN("Missile Cooldown", "Missiles fire more often only.", "A launcher can reload faster.", 4), MISSILE_SPEED("Missile Speed", "Increase missile speed only.", "Rockets can close the distance faster.", 3), EXPLOSION_RADIUS("Explosion Radius", "Increase missile impact radius.", "A blast can reach farther.", 3), MISSILE_COUNT("Missile Count", "Fire one extra missile, up to three total.", "Another launcher tube can be mounted.", 2), SMART_MISSILE_UNLOCK("Smart Missiles", "Missiles acquire living targets.", "A rocket can be taught to think.", 1), SMART_MISSILE_TRACKING("Missile Tracking", "Improve missile target tracking.", "The lock can be strengthened.", 3), SMART_MISSILE_TURN_RATE("Missile Turn Rate", "Missiles turn more quickly.", "Guidance fins can respond faster.", 3), SHRAPNEL_UNLOCK("Shrapnel", "Missile impacts burst into shrapnel.", "A warhead can fracture on impact.", 1), SHRAPNEL_COUNT("Shrapnel Count", "Create more impact fragments.", "The blast could scatter wider.", 3), SHRAPNEL_DAMAGE("Shrapnel Damage", "+1 fragment damage.", "Fragments can be sharpened.", 3), SHRAPNEL_SPEED("Shrapnel Speed", "Increase fragment speed.", "Fragments can fly faster.", 3),
    BLADE_UNLOCK("Blade Unlock", "SPACE throws bouncing blades on its own cooldown.", "A field blade can be issued.", 1), BLADE_DAMAGE("Blade Damage", "+1 blade damage.", "The edge can be honed.", 4), BLADE_COUNT("Blade Count", "Throw one additional blade.", "A second blade could join the volley.", 3), BLADE_THROW_SPEED("Blade Throw Speed", "Increase thrown blade speed.", "A stronger throw reaches farther.", 3), BLADE_LIFETIME("Blade Lifetime", "Keep thrown blades active longer.", "The blade can remain in play.", 3), BLADE_BOUNCE_COUNT("Blade Bounce Count", "Add one wall bounce.", "A ricochet can find another target.", 3), BLADE_SIZE("Blade Size", "Increase blade hitbox and visual size.", "A broader edge can catch more targets.", 3), BLADE_PENETRATION("Blade Penetration", "Hit one additional enemy per blade.", "The edge can cut through a line.", 3), BLADE_RECALL_SPEED("Blade Recovery", "Reduce blade reuse cooldown.", "A quicker recovery readies another throw.", 2),
    CLONE_SUPPORT_UNLOCK("Clone Support", "Deploy one allied backline clone.", "An ally could hold the backline.", 1), ADDITIONAL_CLONE("Additional Clone", "Add one support clone, up to three total.", "More brothers could answer the call.", 2), CLONE_HEALTH("Clone Health", "+3 clone HP.", "Support armor can be reinforced.", 3), CLONE_DAMAGE("Clone Damage", "+1 clone blaster damage.", "Support rifles can be overcharged.", 4), CLONE_FIRE_RATE("Clone Fire Rate", "Increase clone fire speed only.", "Support rifles can cycle faster.", 3), CLONE_ACCURACY("Clone Accuracy", "Clones aim more reliably.", "Discipline can improve their aim.", 3), CLONE_ARMOR("Clone Armor", "Reduce clone damage only.", "Allied plating can be strengthened.", 2), CLONE_REVIVAL("Clone Revival", "Destroyed clones return after a delay.", "Fallen support may return.", 2), CLONE_DISCIPLINE("Clone Discipline", "Clones prioritize threats near the backline.", "The squad can hold formation.", 1),
    DEFENSIVE_LINE_INTEGRITY("Line Integrity", "+3 defensive-line durability.", "The defensive line can be reinforced.", 3), REINFORCED_BARRIER("Reinforced Barrier", "Reduce breach damage.", "The line can absorb a harder impact.", 2), AUTO_REPAIR("Auto Repair", "Slowly restore defensive-line durability.", "Repair crews could maintain the line.", 2),
    CLONE_REINFORCEMENTS("Clone Reinforcements", "Unlock a temporary reinforcement call-in.", "Reinforcements can be called.", 1), ORBITAL_STRIKE("Orbital Strike", "Unlock a targeted lane strike.", "The sky can answer your signal.", 1), AIRSTRIKE("Airstrike", "Unlock a strafing support pass.", "A bomber could make a pass.", 1), NUKE("Nuke", "Unlock a devastating, long-cooldown strike.", "One signal could end an army.", 1);
    private final String title, description, hint; private final int maxLevel;
    UpgradeId(String title, String description, String hint, int maxLevel) { this.title=title; this.description=description; this.hint=hint; this.maxLevel=maxLevel; }
    public String title(){return title;} public String description(){return description;} public String hint(){return hint;} public int maxLevel(){return maxLevel;}
}
