package spaceinvaders.features.campaign;

/** Card definitions. Prerequisites are evaluated by {@link RunUpgrades}. */
public enum UpgradeId {
    MAX_HEALTH("Max Health", "+3 maximum HP and heal 3.", "Stronger armor may help you survive.", 5), ARMOR("Armor", "Reduce incoming damage.", "Plating could soften incoming fire.", 3), MOVEMENT("Movement", "Increase player movement speed only.", "Faster footwork keeps you alive.", 4), RECOVERY("Recovery", "Slowly regenerate health after avoiding damage.", "A medic could keep the squad standing.", 3), XP_GAIN("XP Gain", "Earn 15% more XP per rank.", "Experience can be put to better use.", 3), EMERGENCY_SAVE("Emergency Save", "The first lethal hit leaves you at 1 HP.", "There may be one last chance.", 1),
    BLASTER_DAMAGE("Blaster Damage", "+1 blaster damage.", "More power can be routed to your rifle.", 5), FIRE_RATE("Fire Rate", "Decrease blaster cooldown only.", "Your rifle can cycle faster.", 4), BOLT_SPEED("Bolt Speed", "Increase blaster bolt speed only.", "A faster bolt is harder to evade.", 3), MULTI_SHOT("Multi Shot", "Fire an additional blaster bolt.", "One trigger pull could cover more sky.", 2), PIERCING("Piercing", "Blaster bolts pass through additional enemies.", "A bolt could punch through a formation.", 3), SMART_BULLETS_UNLOCK("Smart Bullets", "Blaster bolts gain gentle target seeking.", "Your shots could learn to hunt.", 1), SMART_BULLET_TRACKING("Smart Tracking", "Improve blaster homing strength.", "A bolt can learn to turn.", 3), SMART_BULLET_RANGE("Smart Range", "Seek targets from farther away.", "A hunter needs a longer view.", 3),
    MISSILE_LAUNCHER("Missile Launcher", "SPACE also fires missiles on its own cooldown.", "A launcher waits in the arsenal.", 1), MISSILE_DAMAGE("Missile Damage", "+2 missile damage.", "A larger warhead awaits.", 4), MISSILE_COOLDOWN("Missile Cooldown", "Missiles fire more often only.", "A launcher can reload faster.", 4), MISSILE_SPEED("Missile Speed", "Increase missile speed only.", "Rockets can close the distance faster.", 3), EXPLOSION_RADIUS("Explosion Radius", "Increase missile impact radius.", "A blast can reach farther.", 3), MISSILE_COUNT("Missile Count", "Fire one extra missile, up to three total.", "Another launcher tube can be mounted.", 2), SMART_MISSILE_UNLOCK("Smart Missiles", "Missiles acquire living targets.", "A rocket can be taught to think.", 1), SMART_MISSILE_TRACKING("Missile Tracking", "Improve missile target tracking.", "The lock can be strengthened.", 3), SMART_MISSILE_TURN_RATE("Missile Turn Rate", "Missiles turn more quickly.", "Guidance fins can respond faster.", 3), SHRAPNEL_UNLOCK("Shrapnel", "Missile impacts burst into shrapnel.", "A warhead can fracture on impact.", 1), SHRAPNEL_COUNT("Shrapnel Count", "Create more impact fragments.", "The blast could scatter wider.", 3), SHRAPNEL_DAMAGE("Shrapnel Damage", "+1 fragment damage.", "Fragments can be sharpened.", 3), SHRAPNEL_SPEED("Shrapnel Speed", "Increase fragment speed.", "Fragments can fly faster.", 3),
    BLADE_UNLOCK("Blade Unlock", "SPACE throws bouncing blades on its own cooldown.", "A field blade can be issued.", 1), BLADE_DAMAGE("Blade Damage", "+1 blade damage.", "The edge can be honed.", 4), BLADE_COUNT("Blade Count", "Throw one additional blade.", "A second blade could join the volley.", 3), BLADE_THROW_SPEED("Blade Throw Speed", "Increase thrown blade speed.", "A stronger throw reaches farther.", 3), BLADE_LIFETIME("Blade Lifetime", "Keep thrown blades active longer.", "The blade can remain in play.", 3), BLADE_BOUNCE_COUNT("Blade Bounce Count", "Add one wall bounce.", "A ricochet can find another target.", 3), BLADE_SIZE("Blade Size", "Increase blade hitbox and visual size.", "A broader edge can catch more targets.", 3), BLADE_PENETRATION("Blade Penetration", "Hit one additional enemy per blade.", "The edge can cut through a line.", 3), BLADE_RECALL_SPEED("Blade Recovery", "Reduce blade reuse cooldown.", "A quicker recovery readies another throw.", 2),
    CLONE_SUPPORT_UNLOCK("Clone Reinforcement Protocol", "Unlock slot 1, grant one reinforcement now, and +1 each mission.", "An ally could hold the backline.", 1), ADDITIONAL_CLONE("Reinforcement Logistics", "Gain +1 additional Clone Reinforcement charge each mission.", "More brothers could answer the call.", 2), CLONE_HEALTH("Clone Vitality", "+5 clone maximum HP and +5 current HP for living clones.", "Support armor can be reinforced.", 3), CLONE_DAMAGE("Clone Blaster Damage", "+1 clone blaster damage.", "Support rifles can be overcharged.", 3), CLONE_FIRE_RATE("Clone Fire Rate", "Increase clone fire speed only.", "Support rifles can cycle faster.", 3), CLONE_ACCURACY("Clone Accuracy", "Clones aim more reliably.", "Discipline can improve their aim.", 2), CLONE_ARMOR("Clone Armor", "Reduce clone damage only.", "Allied plating can be strengthened.", 3), CLONE_REVIVAL("Field Medic", "Surviving clones recover 3 HP between missions.", "A medic could support the line.", 1), CLONE_DISCIPLINE("Clone Formation Training", "Improves clone spacing and backline targeting.", "The squad can hold formation.", 1), HEAVY_REINFORCEMENT_AUTHORIZATION("Heavy Reinforcement Authorization", "Opens the later Republic tank-support branch.", "Heavy support awaits authorization.", 1), TANK_SUPPORT_UNLOCK("Tank Support Unlock", "Placeholder: adds a Republic tank call-in to the reinforcement path.", "A heavier ally could join the line.", 1), TANK_ARMOR("Tank Armor", "Placeholder tank durability tuning.", "Heavy plating could be improved.", 3), TANK_WEAPON_DAMAGE("Tank Weapon Damage", "Placeholder tank weapon tuning.", "A cannon could be upgraded.", 3), TANK_SUPPORT_CHARGES("Tank Support Charges", "Placeholder tank support-charge tuning.", "More logistics could be arranged.", 2), ADVANCED_REPUBLIC_ARMOR("Advanced Republic Armor", "Placeholder final tank-support upgrade.", "The heavy line can be perfected.", 1),
    DEFENSIVE_LINE_INTEGRITY("Line Integrity", "+3 defensive-line durability.", "The defensive line can be reinforced.", 3), REINFORCED_BARRIER("Reinforced Barrier", "Reduce breach damage.", "The line can absorb a harder impact.", 2), AUTO_REPAIR("Auto Repair", "Slowly restore defensive-line durability.", "Repair crews could maintain the line.", 2),
    CLONE_REINFORCEMENTS("Clone Reinforcements", "Unlock a temporary reinforcement call-in.", "Reinforcements can be called.", 1), ORBITAL_STRIKE("Orbital Strike", "Unlock a targeted lane strike.", "The sky can answer your signal.", 1), AIRSTRIKE("Airstrike", "Unlock a strafing support pass.", "A bomber could make a pass.", 1), NUKE("Nuke", "Unlock a devastating, long-cooldown strike.", "One signal could end an army.", 1);
    private final String title, description, hint; private final int maxLevel;
    UpgradeId(String title, String description, String hint, int maxLevel) { this.title=title; this.description=description; this.hint=hint; this.maxLevel=maxLevel; }
    public String title(){return title;} public String description(){return description;} public String hint(){return hint;} public int maxLevel(){return maxLevel;}
    public UpgradePath path() {
        return switch (this) {
            case BLASTER_DAMAGE, FIRE_RATE, BOLT_SPEED, MULTI_SHOT, PIERCING, SMART_BULLETS_UNLOCK, SMART_BULLET_TRACKING, SMART_BULLET_RANGE -> UpgradePath.BLASTER;
            case MISSILE_LAUNCHER, MISSILE_DAMAGE, MISSILE_COOLDOWN, MISSILE_SPEED, EXPLOSION_RADIUS, MISSILE_COUNT, SMART_MISSILE_UNLOCK, SMART_MISSILE_TRACKING, SMART_MISSILE_TURN_RATE, SHRAPNEL_UNLOCK, SHRAPNEL_COUNT, SHRAPNEL_DAMAGE, SHRAPNEL_SPEED -> UpgradePath.MISSILES;
            case BLADE_UNLOCK, BLADE_DAMAGE, BLADE_COUNT, BLADE_THROW_SPEED, BLADE_LIFETIME, BLADE_BOUNCE_COUNT, BLADE_SIZE, BLADE_PENETRATION, BLADE_RECALL_SPEED -> UpgradePath.BLADES;
            case CLONE_SUPPORT_UNLOCK, ADDITIONAL_CLONE, CLONE_HEALTH, CLONE_DAMAGE, CLONE_FIRE_RATE, CLONE_ACCURACY, CLONE_ARMOR, CLONE_REVIVAL, CLONE_DISCIPLINE, HEAVY_REINFORCEMENT_AUTHORIZATION, TANK_SUPPORT_UNLOCK, TANK_ARMOR, TANK_WEAPON_DAMAGE, TANK_SUPPORT_CHARGES, ADVANCED_REPUBLIC_ARMOR, CLONE_REINFORCEMENTS -> UpgradePath.CLONE_REINFORCEMENTS;
            case DEFENSIVE_LINE_INTEGRITY, REINFORCED_BARRIER, AUTO_REPAIR -> UpgradePath.DEFENSIVE_LINE;
            case ORBITAL_STRIKE -> UpgradePath.SUPPORT_ORBITAL;
            case AIRSTRIKE -> UpgradePath.SUPPORT_AIRSTRIKE;
            case NUKE -> UpgradePath.SUPPORT_NUKE;
            default -> UpgradePath.PLAYER;
        };
    }
}
